---
grafana:
  nodeSelector:
    role: infra-node
  persistence:
    enabled: false

prometheus-node-exporter:
  enabled: true

prometheus:
  prometheusSpec:
    nodeSelector:
      role: infra-node
    enableRemoteWriteReceiver: true
    enableAdminApi: true
    retention: 30d
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ebs-prom-ba-2026-sc
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi