--- # Szenario B - Isolate
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: latency-check
  namespace: thesis
spec:
  args:
    - name: latest-hash
  metrics:
    - name: latency
      interval: 60s
      failureLimit: 1
      failureCondition: len(result) > 0 && result[0] > 15
      provider:
        prometheus:
          address: http://kube-prometheus-kube-prome-prometheus.monitoring.svc.cluster.local:9090
          query: |
            avg(avg_over_time(ktor_http_server_requests_seconds{
              quantile="0.95", pod=~".*{{args.latest-hash}}.*"}[1m])
            ) * 1000