---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: shop-service-rollout
  namespace: thesis
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 10
        - pause: { duration: 5m }
        - setWeight: 50
        - pause: { duration: 5m }
        - setWeight: 75
        - pause: { duration: 5m }
        - setWeight: 100
        - pause: { }
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
        version: canary
    spec:
      nodeSelector:
        role: app-node
      containers:
        - name: shop
          image: ghcr.io/vulnerius/shop-service:v1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: VERSION
              value: "canary"
            - name: ERROR_RATE
              value: "0"
            - name: LATENCY
              value: "0"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx512m -Xms256m"
            - name: PAYMENT_SERVICE_URL
              value: "http://transaction-service.thesis.svc.cluster.local/pay"
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "200m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh", "-c", "sleep 10" ]
      imagePullSecrets:
        - name: ghcr-image-pull-secret