--- # Szenario A - Global
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate-check
  namespace: thesis
spec:
  args:
    - name: service-name
  metrics:
    - name: error-rate
      interval: 60s
      failureLimit: 1
      failureCondition: len(result) > 0 && result[0] > 1
      provider:
        prometheus:
          address: http://kube-prometheus-kube-prome-prometheus.monitoring.svc.cluster.local:9090
          query: |
            ( sum(rate(k6_http_reqs_total{status="500", group="::{{args.service-name}}"}[1m]))
              /
            sum(rate(k6_http_reqs_total{group="::{{args.service-name}}"}[1m])) ) * 100
# k6_http_req_failed_rate{group="::transaction"}
# k6_http_req_failed_rate{group="::shop"}

--- # Szenario A - Isolate
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate-check
  namespace: thesis
spec:
  args:
    - name: latest-hash
  metrics:
    - name: error-rate
      interval: 60s
      failureLimit: 1
      failureCondition: len(result) > 0 && result[0] > 1
      provider:
        prometheus:
          address: http://kube-prometheus-kube-prome-prometheus.monitoring.svc.cluster.local:9090
          query: |
            (sum(rate(ktor_http_server_requests_seconds_count{status="500", pod=~".*{{args.latest-hash}}.*"}[1m])) 
              /
            (sum(rate(ktor_http_server_requests_seconds_count{pod=~".*{{args.latest-hash}}.*"}[1m])))) * 100

--- # Szenario B - Global
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: latency-check
  namespace: thesis
spec:
  args:
    - name: service-name
  metrics:
    - name: p95-latency
      interval: 60s
      failureLimit: 1
      failureCondition: result[0] > 15
      provider:
        prometheus:
          address: http://kube-prometheus-kube-prome-prometheus.monitoring.svc.cluster.local:9090
          query: |
            avg(avg_over_time(k6_http_req_duration_p95{group="::{{args.service-name}}", status="200"}[1m]))*1000
# k6_http_req_duration_p95{group="::transaction"}
# k6_http_req_duration_p95{group="::shop"}

--- # Szenario B - Isolate
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: latency-check
  namespace: thesis
spec:
  args:
    - name: latest-hash
  metrics:
    - name: p95-latency
      interval: 60s
      failureLimit: 1
      failureCondition: result[0] > 15
      provider:
        prometheus:
          address: http://kube-prometheus-kube-prome-prometheus.monitoring.svc.cluster.local:9090
          query: |
            avg(avg_over_time(ktor_http_server_requests_seconds{
              quantile="0.95", pod=~".*{{args.latest-hash}}.*", status="200", route="/pay"
            }[1m])) * 1000
