{
 "title": "Custom Evaluation Dashboard",
 "time": { "from": "2026-03-11T00:00:00.000Z", "to": "2026-03-15T23:59:59.000Z" },
 "panels": [
  {
   "title": "sum Errors per 1 min",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (group) (increase(k6_http_reqs_total{status=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total requests per min",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (group) (increase(k6_http_reqs_total[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "K6 req duration p95 per 1 min",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by (group) (\n  avg_over_time(k6_http_req_duration_p95{status=\"200\"}[1m])\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sum k6-errors per 1m",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(ktor_http_server_requests_seconds_count{status=\"500\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sum rate k6-errors per 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs_total{status=\"500\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error_rate per 1 min",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "(sum by (group) (rate(k6_http_reqs_total{status=~\"5..\"}[1m])) \n/ \nsum by (group) (rate(k6_http_reqs_total[1m]))) \n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sum error-requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(ktor_http_server_requests_seconds_count{status=\"500\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}