---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-cm-bm-30m-test
  namespace: thesis-load-test
data:
  test.js: |
    import http from 'k6/http';
    import {check, group} from 'k6';
    
    export const options = {
        scenarios: {
            baseline_load: {
                executor: 'constant-arrival-rate',
                rate: 1200,
                timeUnit: '1s',
                preAllocatedVUs: 300,
                maxVUs: 1000,
                duration: "30m"
            },
        }
    };
    
    export default function () {
        group('shop', function () {
            const resShop = http.get('http://shop-service.thesis.svc.cluster.local/shop');
            check(resShop, {
                'shop service response status is 200': (r) => r.status === 200 ,
                'shop version is stable': resShop.body.toString().includes("version: stable")
            });
        })
        
        group('transaction', function () {
            const resTrans = http.get('http://transaction-service.thesis.svc.cluster.local/pay');
            check(resTrans,{
                'transaction service response status is 200': (r) => r.status === 200,
                'transaction version is stable': (res) => res.body.toString().includes("version: stable")
            });
        })
    }