---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-cm-bm-120m-test
  namespace: thesis-load-test
data:
  test.js: |
    import http from 'k6/http';
    import {check, sleep} from 'k6';
    
    export const options = {
        scenarios: {
            baseline_load: {
                executor: 'constant-arrival-rate',
                rate: 1200,
                timeUnit: '1s',
                preAllocatedVUs: 300,
                maxVUs: 1000,
                duration: "120m"
            },
        },
    };
    
    export default function () {
        // shop
        const resShop = http.get('http://shop-service.thesis.svc.cluster.local/shop');
        check(resShop, {
            'shop service response status is 200': (r) => r.status === 200
        });
        // transaction
        const resTrans = http.get('http://transaction-service.thesis.svc.cluster.local/pay');
        check(resTrans, {'transaction service response status is 200': (r) => r.status === 200});
        sleep(.3)
    }