---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: transaction-service-rollout
  namespace: thesis
spec:
  replicas: 3
  minReadySeconds: 20
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      labels:
        app: transaction
        version: rolling
    spec:
      nodeSelector:
        role: app-node
      containers:
        - name: transaction
          image: ghcr.io/vulnerius/transaction-service:v1.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: VERSION
              value: "rolling"
            - name: ERROR_RATE
              value: "0.01"
            - name: LATENCY
              value: "0"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx512m -Xms256m"
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "250m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 20"]
      imagePullSecrets:
        - name: ghcr-image-pull-secret
  strategy:
    canary:
      maxSurge: 1
      maxUnavailable: 0