---
name: Manual Experiment v1.1 Failure Injection per service - rollout fail after 60s
on:
  push:
    branches: [ "release" ]
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Which service to target?'
        required: true
        default: 'transaction-service'
        type: choice
        options:
          - transaction-service
          - shop-service
      error_rate:
        description: 'Error Rate of Http-Responses (0.0 - 1.0)'
        required: true
        default: '0.0'
      latency:
        description: 'simulated latency in ms'
        required: true
        default: '0'

jobs:
  deploy-experiment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          # audience: sts.amazonaws.com
          role-to-assume: ${{ vars.ROLLOUT_AWS_ROLE_ARN }}
          aws-region: eu-central-1

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name ba-2026-eks

      - name: Inject Variables and Patch Rollout
        run: |
          echo "starting rollout for service ${{ github.event.inputs.service_name }}..."
          
          kubectl patch rollout ${{ github.event.inputs.service_name }}-rollout --type='json' -p='[
            {"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "/${{ github.event.inputs.service_name }}:v1.1"},
            {"op": "replace", "path": "/spec/template/spec/containers/0/env", "value": [
              {"name": "ERROR_RATE", "value": "${{ github.event.inputs.failure_rate }}"},
              {"name": "LATENCY", "value": "${{ github.event.inputs.latency_ms }}"}
            ]}
          ]'

      - name: Monitor Rollout
        run: kubectl argo rollouts get rollout ${{ github.event.inputs.service_name }}-rollout --watch --timeout-seconds 60

permissions:
  id-token: write
  contents: read